apiVersion: v1
kind: Secret
metadata:
  name: snsf-secrets
  namespace: default
  labels:
    app: snsf-backend
    environment: production
type: Opaque
data:
  db-host: "cG9zdGdyZXMtc2VydmljZQ=="
  db-user: "cG9zdGdyZXM="
  db-password: "c2FudHVhcmlvMTIz"
  db-name: "c25zZl9kYg=="
  jwt-secret: "bWluaGFNoYXZlU2VjcmV0YQ=="